robot2_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - robot2_elbow_joint
     - robot2_shoulder_lift_joint
     - robot2_shoulder_pan_joint
     - robot2_wrist_1_joint
     - robot2_wrist_2_joint
     - robot2_wrist_3_joint
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      robot2_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      robot2_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      robot2_elbow_joint: {trajectory: 0.1, goal: 0.1}
      robot2_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
      robot2_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
      robot2_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  50
  action_monitor_rate: 10
